package it.trrileva.exportTracciato;

import java.awt.Color;
import java.awt.Font;
import java.io.File;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author francesco
 */
public class ExportTracciatoUI extends javax.swing.JFrame {


	private static final long serialVersionUID = 4774079820238077077L;
	
	private File selectedFile;
    /**
     * Creates new form ExportTracciatoUI
     */
    public ExportTracciatoUI() {
    	setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboCodiceDitta = new javax.swing.JComboBox<>();
        jComboMese = new javax.swing.JComboBox<>();
        jComboMese.setToolTipText("");
        jComboAnno = new javax.swing.JComboBox<>();
        selezionaFileButton = new javax.swing.JButton();
        filePathLabel = new javax.swing.JLabel();
        ElaboraButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(102, 205, 170));

        jPanel2.setBackground(new Color(102, 205, 170));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jComboCodiceDitta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboCodiceDitta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RC10001", "RC11010", "RC11011", "RC10059", "RC10009" }));

        jComboMese.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboMese.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));


        jComboAnno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboAnno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022" }));

        selezionaFileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selezionaFileButton.setText("Seleziona file");
        selezionaFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaFileButtonActionPerformed(evt);
            }
        });

        ElaboraButton.setBackground(new Color(102, 205, 170));
        ElaboraButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ElaboraButton.setText("ELABORA");
        ElaboraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElaboraButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("ANNO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("MESE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("CODICE DITTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(35)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(selezionaFileButton)
        					.addGap(18)
        					.addComponent(filePathLabel, GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addComponent(jLabel2)
        						.addComponent(jLabel1))
        					.addGap(9)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jComboAnno, 0, 413, Short.MAX_VALUE)
        						.addComponent(jComboMese, 0, 413, Short.MAX_VALUE)
        						.addComponent(jComboCodiceDitta, 0, 413, Short.MAX_VALUE))))
        			.addGap(47))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(83, Short.MAX_VALUE)
        			.addComponent(ElaboraButton, GroupLayout.PREFERRED_SIZE, 467, GroupLayout.PREFERRED_SIZE)
        			.addGap(88))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(36)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboAnno, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboMese, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jComboCodiceDitta, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
        			.addGap(41)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(filePathLabel, GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        				.addComponent(selezionaFileButton, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
        			.addGap(44)
        			.addComponent(ElaboraButton, GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        			.addGap(74))
        );
        jPanel1.setLayout(jPanel1Layout);
        
        JLabel lblNewLabel = new JLabel("Esporta Tracciato Sequenziale");
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(91)
        			.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(99))
        		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(38)
        			.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        			.addGap(18)
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 580, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElaboraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElaboraButtonActionPerformed
    	try{
            if(jComboCodiceDitta.getItemAt(jComboCodiceDitta.getSelectedIndex()).equals("RC10001")){
                ExportTracciato.execute(jComboMese.getItemAt(jComboMese.getSelectedIndex()), jComboAnno.getItemAt(jComboAnno.getSelectedIndex()), jComboCodiceDitta.getItemAt(jComboCodiceDitta.getSelectedIndex()), selectedFile.getAbsolutePath());
            } else {
                ExportTracciato2.execute(jComboMese.getItemAt(jComboMese.getSelectedIndex()), jComboAnno.getItemAt(jComboAnno.getSelectedIndex()), jComboCodiceDitta.getItemAt(jComboCodiceDitta.getSelectedIndex()), selectedFile.getAbsolutePath());
            }
            JOptionPane.showMessageDialog(null, "file .seq creato correttamente");
        } catch (Exception e) {
    		JOptionPane.showMessageDialog(null, "Errore nella genarazione del file: " + e.getMessage());
		}
    }//GEN-LAST:event_ElaboraButtonActionPerformed

    private void selezionaFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        
        int response = fileChooser.showOpenDialog(null);
        
        if(response == JFileChooser.APPROVE_OPTION) {
            selectedFile = new File(fileChooser.getSelectedFile().getAbsolutePath());
            filePathLabel.setText(selectedFile.getName());
            System.out.println(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_selezionaFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportTracciatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportTracciatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportTracciatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportTracciatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportTracciatoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ElaboraButton;
    private javax.swing.JLabel filePathLabel;
    private javax.swing.JComboBox<String> jComboAnno;
    private javax.swing.JComboBox<String> jComboCodiceDitta;
    private javax.swing.JComboBox<String> jComboMese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton selezionaFileButton;
}
